[build]
  command = "npx expo export --platform web"
  publish = "dist"

[[headers]]
  for = "/_expo/static/js/*"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
